Node*	alloc_node(Symbol*);
Symbol*	alloc_func(char*);
Symbol*	alloc_num(double);
Symbol*	alloc_var(char);
void	ast_cleanup(Node*);
Node*	ast_insert(Node*, Node*);
Node*	ast_insert_above(Node*, Node*);
void	cleanup(void);
void*	ecalloc(long, size_t);
void*	emalloc(size_t);
void	p_cleanup(Parser*);
Parser*	p_init(char*);
int	parse(Parser*);
void	print_symbol(Symbol*);
void	print_tree(Node*);
char*	readall(FILE*);
size_t	strappend(char*, char, size_t, size_t);
